package PDFApp;


/**
* PDFApp/_PDFServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:24 PM GMT
*/

public class _PDFServiceStub extends org.omg.CORBA.portable.ObjectImpl implements PDFApp.PDFService
{


  // Fusion de plusieurs PDFs en un seul
  public byte[] fusionnerPDFs (byte[][] pdfs) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("fusionnerPDFs", true);
                PDFApp.PDFListHelper.write ($out, pdfs);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return fusionnerPDFs (pdfs        );
            } finally {
                _releaseReply ($in);
            }
  } // fusionnerPDFs


  // Découpage d'un PDF en plusieurs
  public byte[][] decouperPDF (byte[] pdf, int nbPages) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("decouperPDF", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_long (nbPages);
                $in = _invoke ($out);
                byte $result[][] = PDFApp.PDFListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return decouperPDF (pdf, nbPages        );
            } finally {
                _releaseReply ($in);
            }
  } // decouperPDF


  // Extraction de pages spécifiques
  public byte[] extrairePages (byte[] pdf, int[] pages) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extrairePages", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                PDFApp.PageListHelper.write ($out, pages);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extrairePages (pdf, pages        );
            } finally {
                _releaseReply ($in);
            }
  } // extrairePages


  // Suppression de pages
  public byte[] supprimerPages (byte[] pdf, int[] pages) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerPages", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                PDFApp.PageListHelper.write ($out, pages);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return supprimerPages (pdf, pages        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerPages


  // Ajout de mot de passe
  public byte[] ajouterMotDePasse (byte[] pdf, String motDePasse) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterMotDePasse", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_string (motDePasse);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterMotDePasse (pdf, motDePasse        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterMotDePasse


  // Conversion PDF en images (retourne liste d'images PNG)
  public byte[][] convertirEnImages (byte[] pdf, int dpi) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("convertirEnImages", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_long (dpi);
                $in = _invoke ($out);
                byte $result[][] = PDFApp.PDFListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return convertirEnImages (pdf, dpi        );
            } finally {
                _releaseReply ($in);
            }
  } // convertirEnImages


  // Extraction de texte
  public String extraireTexte (byte[] pdf) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extraireTexte", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extraireTexte (pdf        );
            } finally {
                _releaseReply ($in);
            }
  } // extraireTexte


  // Création d'un PDF depuis du texte
  public byte[] creerPDF (String titre, String contenu) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerPDF", true);
                $out.write_string (titre);
                $out.write_string (contenu);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerPDF (titre, contenu        );
            } finally {
                _releaseReply ($in);
            }
  } // creerPDF


  // Compression du PDF
  public byte[] compresserPDF (byte[] pdf) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("compresserPDF", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return compresserPDF (pdf        );
            } finally {
                _releaseReply ($in);
            }
  } // compresserPDF


  // Lire les métadonnées
  public String lireMetadonnees (byte[] pdf) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("lireMetadonnees", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return lireMetadonnees (pdf        );
            } finally {
                _releaseReply ($in);
            }
  } // lireMetadonnees


  // Modifier les métadonnées
  public byte[] modifierMetadonnees (byte[] pdf, String titre, String auteur, String sujet) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifierMetadonnees", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_string (titre);
                $out.write_string (auteur);
                $out.write_string (sujet);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modifierMetadonnees (pdf, titre, auteur, sujet        );
            } finally {
                _releaseReply ($in);
            }
  } // modifierMetadonnees


  // Ajouter un QR Code
  public byte[] ajouterQRCode (byte[] pdf, String contenu, int page, int x, int y) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterQRCode", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_string (contenu);
                $out.write_long (page);
                $out.write_long (x);
                $out.write_long (y);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterQRCode (pdf, contenu, page, x, y        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterQRCode


  // Signature numérique
  public byte[] signerPDF (byte[] pdf, String nomSignataire, String raison, String lieu) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("signerPDF", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_string (nomSignataire);
                $out.write_string (raison);
                $out.write_string (lieu);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return signerPDF (pdf, nomSignataire, raison, lieu        );
            } finally {
                _releaseReply ($in);
            }
  } // signerPDF

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFApp/PDFService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PDFApp._PDFServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PDFServiceStub
