package PDFApp;


/**
* PDFApp/PageListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:23 PM GMT
*/

public final class PageListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public PageListHolder ()
  {
  }

  public PageListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFApp.PageListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFApp.PageListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFApp.PageListHelper.type ();
  }

}
