package PDFApp;


/**
* PDFApp/PDFDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:23 PM GMT
*/

public final class PDFDataHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public PDFDataHolder ()
  {
  }

  public PDFDataHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFApp.PDFDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFApp.PDFDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFApp.PDFDataHelper.type ();
  }

}
