package PDFApp;

/**
* PDFApp/PDFExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:23 PM GMT
*/

public final class PDFExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFApp.PDFException value = null;

  public PDFExceptionHolder ()
  {
  }

  public PDFExceptionHolder (PDFApp.PDFException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFApp.PDFExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFApp.PDFExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFApp.PDFExceptionHelper.type ();
  }

}
