package PDFApp;


/**
* PDFApp/PDFException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:23 PM GMT
*/

public final class PDFException extends org.omg.CORBA.UserException
{
  public String message = null;

  public PDFException ()
  {
    super(PDFExceptionHelper.id());
  } // ctor

  public PDFException (String _message)
  {
    super(PDFExceptionHelper.id());
    message = _message;
  } // ctor


  public PDFException (String $reason, String _message)
  {
    super(PDFExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class PDFException
