package PDFApp;


/**
* PDFApp/PDFListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:23 PM GMT
*/

public final class PDFListHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[][] = null;

  public PDFListHolder ()
  {
  }

  public PDFListHolder (byte[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFApp.PDFListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFApp.PDFListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFApp.PDFListHelper.type ();
  }

}
