package PDFApp;


/**
* PDFApp/PDFServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:24 PM GMT
*/

public abstract class PDFServicePOA extends org.omg.PortableServer.Servant
 implements PDFApp.PDFServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fusionnerPDFs", new java.lang.Integer (0));
    _methods.put ("decouperPDF", new java.lang.Integer (1));
    _methods.put ("extrairePages", new java.lang.Integer (2));
    _methods.put ("supprimerPages", new java.lang.Integer (3));
    _methods.put ("ajouterMotDePasse", new java.lang.Integer (4));
    _methods.put ("convertirEnImages", new java.lang.Integer (5));
    _methods.put ("extraireTexte", new java.lang.Integer (6));
    _methods.put ("creerPDF", new java.lang.Integer (7));
    _methods.put ("compresserPDF", new java.lang.Integer (8));
    _methods.put ("lireMetadonnees", new java.lang.Integer (9));
    _methods.put ("modifierMetadonnees", new java.lang.Integer (10));
    _methods.put ("ajouterQRCode", new java.lang.Integer (11));
    _methods.put ("signerPDF", new java.lang.Integer (12));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Fusion de plusieurs PDFs en un seul
       case 0:  // PDFApp/PDFService/fusionnerPDFs
       {
         try {
           byte pdfs[][] = PDFApp.PDFListHelper.read (in);
           byte $result[] = null;
           $result = this.fusionnerPDFs (pdfs);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Découpage d'un PDF en plusieurs
       case 1:  // PDFApp/PDFService/decouperPDF
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           int nbPages = in.read_long ();
           byte $result[][] = null;
           $result = this.decouperPDF (pdf, nbPages);
           out = $rh.createReply();
           PDFApp.PDFListHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Extraction de pages spécifiques
       case 2:  // PDFApp/PDFService/extrairePages
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           int pages[] = PDFApp.PageListHelper.read (in);
           byte $result[] = null;
           $result = this.extrairePages (pdf, pages);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Suppression de pages
       case 3:  // PDFApp/PDFService/supprimerPages
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           int pages[] = PDFApp.PageListHelper.read (in);
           byte $result[] = null;
           $result = this.supprimerPages (pdf, pages);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Ajout de mot de passe
       case 4:  // PDFApp/PDFService/ajouterMotDePasse
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String motDePasse = in.read_string ();
           byte $result[] = null;
           $result = this.ajouterMotDePasse (pdf, motDePasse);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Conversion PDF en images (retourne liste d'images PNG)
       case 5:  // PDFApp/PDFService/convertirEnImages
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           int dpi = in.read_long ();
           byte $result[][] = null;
           $result = this.convertirEnImages (pdf, dpi);
           out = $rh.createReply();
           PDFApp.PDFListHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Extraction de texte
       case 6:  // PDFApp/PDFService/extraireTexte
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String $result = null;
           $result = this.extraireTexte (pdf);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Création d'un PDF depuis du texte
       case 7:  // PDFApp/PDFService/creerPDF
       {
         try {
           String titre = in.read_string ();
           String contenu = in.read_string ();
           byte $result[] = null;
           $result = this.creerPDF (titre, contenu);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Compression du PDF
       case 8:  // PDFApp/PDFService/compresserPDF
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           byte $result[] = null;
           $result = this.compresserPDF (pdf);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Lire les métadonnées
       case 9:  // PDFApp/PDFService/lireMetadonnees
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String $result = null;
           $result = this.lireMetadonnees (pdf);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Modifier les métadonnées
       case 10:  // PDFApp/PDFService/modifierMetadonnees
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String titre = in.read_string ();
           String auteur = in.read_string ();
           String sujet = in.read_string ();
           byte $result[] = null;
           $result = this.modifierMetadonnees (pdf, titre, auteur, sujet);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Ajouter un QR Code
       case 11:  // PDFApp/PDFService/ajouterQRCode
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String contenu = in.read_string ();
           int page = in.read_long ();
           int x = in.read_long ();
           int y = in.read_long ();
           byte $result[] = null;
           $result = this.ajouterQRCode (pdf, contenu, page, x, y);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // Signature numérique
       case 12:  // PDFApp/PDFService/signerPDF
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String nomSignataire = in.read_string ();
           String raison = in.read_string ();
           String lieu = in.read_string ();
           byte $result[] = null;
           $result = this.signerPDF (pdf, nomSignataire, raison, lieu);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFApp/PDFService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PDFService _this() 
  {
    return PDFServiceHelper.narrow(
    super._this_object());
  }

  public PDFService _this(org.omg.CORBA.ORB orb) 
  {
    return PDFServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PDFServicePOA
