package PDFApp;


/**
* PDFApp/PDFServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:24 PM GMT
*/

public interface PDFServiceOperations 
{

  // Fusion de plusieurs PDFs en un seul
  byte[] fusionnerPDFs (byte[][] pdfs) throws PDFApp.PDFException;

  // Découpage d'un PDF en plusieurs
  byte[][] decouperPDF (byte[] pdf, int nbPages) throws PDFApp.PDFException;

  // Extraction de pages spécifiques
  byte[] extrairePages (byte[] pdf, int[] pages) throws PDFApp.PDFException;

  // Suppression de pages
  byte[] supprimerPages (byte[] pdf, int[] pages) throws PDFApp.PDFException;

  // Ajout de mot de passe
  byte[] ajouterMotDePasse (byte[] pdf, String motDePasse) throws PDFApp.PDFException;

  // Conversion PDF en images (retourne liste d'images PNG)
  byte[][] convertirEnImages (byte[] pdf, int dpi) throws PDFApp.PDFException;

  // Extraction de texte
  String extraireTexte (byte[] pdf) throws PDFApp.PDFException;

  // Création d'un PDF depuis du texte
  byte[] creerPDF (String titre, String contenu) throws PDFApp.PDFException;

  // Compression du PDF
  byte[] compresserPDF (byte[] pdf) throws PDFApp.PDFException;

  // Lire les métadonnées
  String lireMetadonnees (byte[] pdf) throws PDFApp.PDFException;

  // Modifier les métadonnées
  byte[] modifierMetadonnees (byte[] pdf, String titre, String auteur, String sujet) throws PDFApp.PDFException;

  // Ajouter un QR Code
  byte[] ajouterQRCode (byte[] pdf, String contenu, int page, int x, int y) throws PDFApp.PDFException;

  // Signature numérique
  byte[] signerPDF (byte[] pdf, String nomSignataire, String raison, String lieu) throws PDFApp.PDFException;
} // interface PDFServiceOperations
