package PDFApp;

/**
* PDFApp/PDFServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, May 6, 2026 11:52:24 PM GMT
*/

public final class PDFServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFApp.PDFService value = null;

  public PDFServiceHolder ()
  {
  }

  public PDFServiceHolder (PDFApp.PDFService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFApp.PDFServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFApp.PDFServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFApp.PDFServiceHelper.type ();
  }

}
