package PDFApp;


/**
* PDFApp/_PDFServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/PDFApp/PDFApp.idl
* Wednesday, April 29, 2026 10:38:42 AM GMT
*/

public class _PDFServiceStub extends org.omg.CORBA.portable.ObjectImpl implements PDFApp.PDFService
{


  // Services demandés sur le schéma
  public byte[] creerPDF (String titre, String contenu) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerPDF", true);
                $out.write_string (titre);
                $out.write_string (contenu);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerPDF (titre, contenu        );
            } finally {
                _releaseReply ($in);
            }
  } // creerPDF

  public byte[] fusionnerPDF (byte[] pdf1, byte[] pdf2) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("fusionnerPDF", true);
                PDFApp.PDFDataHelper.write ($out, pdf1);
                PDFApp.PDFDataHelper.write ($out, pdf2);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return fusionnerPDF (pdf1, pdf2        );
            } finally {
                _releaseReply ($in);
            }
  } // fusionnerPDF

  public byte[] decouperPDF (byte[] pdf, int pageDebut, int pageFin) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("decouperPDF", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_long (pageDebut);
                $out.write_long (pageFin);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return decouperPDF (pdf, pageDebut, pageFin        );
            } finally {
                _releaseReply ($in);
            }
  } // decouperPDF

  public String extraireTexte (byte[] pdf) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extraireTexte", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extraireTexte (pdf        );
            } finally {
                _releaseReply ($in);
            }
  } // extraireTexte

  public byte[] supprimerPages (byte[] pdf, int numeroPage) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerPages", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_long (numeroPage);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return supprimerPages (pdf, numeroPage        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerPages

  public byte[] ajouterMotDePasse (byte[] pdf, String password) throws PDFApp.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterMotDePasse", true);
                PDFApp.PDFDataHelper.write ($out, pdf);
                $out.write_string (password);
                $in = _invoke ($out);
                byte $result[] = PDFApp.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFApp/PDFException:1.0"))
                    throw PDFApp.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterMotDePasse (pdf, password        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterMotDePasse

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFApp/PDFService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PDFApp._PDFServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PDFServiceStub
