package PDFApp;


/**
* PDFApp/PDFException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/PDFApp/PDFApp.idl
* Wednesday, April 29, 2026 10:38:42 AM GMT
*/

public final class PDFException extends org.omg.CORBA.UserException
{
  public String why = null;

  public PDFException ()
  {
    super(PDFExceptionHelper.id());
  } // ctor

  public PDFException (String _why)
  {
    super(PDFExceptionHelper.id());
    why = _why;
  } // ctor


  public PDFException (String $reason, String _why)
  {
    super(PDFExceptionHelper.id() + "  " + $reason);
    why = _why;
  } // ctor

} // class PDFException
