package PDFApp;


/**
* PDFApp/PDFServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/PDFApp/PDFApp.idl
* Wednesday, April 29, 2026 10:38:42 AM GMT
*/

public interface PDFServiceOperations 
{

  // Services demandés sur le schéma
  byte[] creerPDF (String titre, String contenu) throws PDFApp.PDFException;
  byte[] fusionnerPDF (byte[] pdf1, byte[] pdf2) throws PDFApp.PDFException;
  byte[] decouperPDF (byte[] pdf, int pageDebut, int pageFin) throws PDFApp.PDFException;
  String extraireTexte (byte[] pdf) throws PDFApp.PDFException;
  byte[] supprimerPages (byte[] pdf, int numeroPage) throws PDFApp.PDFException;
  byte[] ajouterMotDePasse (byte[] pdf, String password) throws PDFApp.PDFException;
} // interface PDFServiceOperations
