package PDFApp;


/**
* PDFApp/PDFServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/PDFApp/PDFApp.idl
* Wednesday, April 29, 2026 10:38:42 AM GMT
*/

public abstract class PDFServicePOA extends org.omg.PortableServer.Servant
 implements PDFApp.PDFServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("creerPDF", new java.lang.Integer (0));
    _methods.put ("fusionnerPDF", new java.lang.Integer (1));
    _methods.put ("decouperPDF", new java.lang.Integer (2));
    _methods.put ("extraireTexte", new java.lang.Integer (3));
    _methods.put ("supprimerPages", new java.lang.Integer (4));
    _methods.put ("ajouterMotDePasse", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Services demandés sur le schéma
       case 0:  // PDFApp/PDFService/creerPDF
       {
         try {
           String titre = in.read_string ();
           String contenu = in.read_string ();
           byte $result[] = null;
           $result = this.creerPDF (titre, contenu);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // PDFApp/PDFService/fusionnerPDF
       {
         try {
           byte pdf1[] = PDFApp.PDFDataHelper.read (in);
           byte pdf2[] = PDFApp.PDFDataHelper.read (in);
           byte $result[] = null;
           $result = this.fusionnerPDF (pdf1, pdf2);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // PDFApp/PDFService/decouperPDF
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           int pageDebut = in.read_long ();
           int pageFin = in.read_long ();
           byte $result[] = null;
           $result = this.decouperPDF (pdf, pageDebut, pageFin);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // PDFApp/PDFService/extraireTexte
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String $result = null;
           $result = this.extraireTexte (pdf);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // PDFApp/PDFService/supprimerPages
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           int numeroPage = in.read_long ();
           byte $result[] = null;
           $result = this.supprimerPages (pdf, numeroPage);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // PDFApp/PDFService/ajouterMotDePasse
       {
         try {
           byte pdf[] = PDFApp.PDFDataHelper.read (in);
           String password = in.read_string ();
           byte $result[] = null;
           $result = this.ajouterMotDePasse (pdf, password);
           out = $rh.createReply();
           PDFApp.PDFDataHelper.write (out, $result);
         } catch (PDFApp.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFApp.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFApp/PDFService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PDFService _this() 
  {
    return PDFServiceHelper.narrow(
    super._this_object());
  }

  public PDFService _this(org.omg.CORBA.ORB orb) 
  {
    return PDFServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PDFServicePOA
