package PDFApp;


/**
* PDFApp/PDFService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/PDFApp/PDFApp.idl
* Wednesday, April 29, 2026 10:38:42 AM GMT
*/

public interface PDFService extends PDFServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PDFService
